apiVersion: v1
kind: Secret
metadata:
   name: drupal-mysql-secret
type: Opaque
data:
   MYSQL_ROOT_PASSWORD: "cm9vdF9wYXNzd29yZA==" # PWD encoded bas64
   MYSQL_DATABASE: "ZHJ1cGFsLWRhdGFiYXNl" # DB encoded bas64
   MYSQL_USER: "cm9vdA==" # User encoded bas64