apiVersion: v1
kind: Secret
metadata:
   name: drupal-mysql-secret
type: Opaque
data:
   MYSQL_ROOT_PASSWORD: # PWD encoded bas64
   MYSQL_DATABASE: # DB encoded bas64
   MYSQL_USER: # User encoded bas64