apiVersion: v1
kind: PersistentVolume
metadata:
   name: redis03
spec:
   storageClassName: manual
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteOnce
   hostPath: 
      path: "/redis03"